// SPDX-License-Identifier: MIT
//
// test_mel_extractor — gates the C++ MelExtractor against the golden mels
// generated by `scripts/generate_golden_mels.py` (raw float32 *.pcm.f32 /
// *.mel.f32 / *.json triplets under `tests/golden_mels/`).
//
// Pass criterion: every case has `max_abs_diff <= 1e-3` and `mean_abs_diff
// <= 1e-4` (the latter is informational; only `max_abs_diff` gates).
//
// Usage:
//   test_mel_extractor <settings.json> <mel_filters.bin> <golden_dir>
//
// Returns non-zero on first failure (after printing the table).
#include "../mel_extractor.h"

#include <algorithm>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <string>
#include <vector>

#include <nlohmann/json.hpp>

namespace fs = std::filesystem;
using Json = nlohmann::json;

namespace {

std::vector<float> readF32(fs::path const& p)
{
    std::ifstream f(p, std::ios::binary | std::ios::ate);
    if (!f) throw std::runtime_error("cannot open " + p.string());
    std::streamsize n = f.tellg();
    f.seekg(0, std::ios::beg);
    std::vector<float> out(static_cast<size_t>(n / sizeof(float)));
    if (n > 0) f.read(reinterpret_cast<char*>(out.data()), n);
    return out;
}

struct CaseResult
{
    std::string name;
    int32_t pcm_samples{0};
    int32_t expected_frames{0};
    int32_t got_frames{0};
    float max_abs_diff{0.0f};
    float mean_abs_diff{0.0f};
    int32_t first_bad_m{-1};
    int32_t first_bad_t{-1};
    float first_bad_expected{0.0f};
    float first_bad_got{0.0f};
    bool pass{false};
};

CaseResult evaluate(MelExtractor const& mel, fs::path const& dir, std::string const& name,
                    float tol)
{
    CaseResult r;
    r.name = name;
    fs::path const pcm_path = dir / (name + ".pcm.f32");
    fs::path const mel_path = dir / (name + ".mel.f32");
    fs::path const meta_path = dir / (name + ".json");

    auto pcm = readF32(pcm_path);
    auto golden = readF32(mel_path);
    std::ifstream js(meta_path);
    if (!js) throw std::runtime_error("cannot open " + meta_path.string());
    Json meta;
    js >> meta;
    auto const shape = meta["mel_shape"];
    int32_t const n_mels = shape[0].get<int>();
    int32_t const n_frames_exp = shape[1].get<int>();
    r.pcm_samples = static_cast<int32_t>(pcm.size());
    r.expected_frames = n_frames_exp;

    int32_t got_frames = 0;
    auto got = mel.compute(pcm, &got_frames);
    r.got_frames = got_frames;
    if (got_frames != n_frames_exp || n_mels != mel.n_mels())
    {
        r.pass = false;
        return r;
    }
    if (static_cast<size_t>(n_mels) * static_cast<size_t>(n_frames_exp) != golden.size())
    {
        r.pass = false;
        return r;
    }

    double sum_abs = 0.0;
    float max_abs = 0.0f;
    for (size_t i = 0; i < got.size(); ++i)
    {
        float const d = std::abs(got[i] - golden[i]);
        if (d > max_abs)
        {
            max_abs = d;
            int32_t const m = static_cast<int32_t>(i) / n_frames_exp;
            int32_t const t = static_cast<int32_t>(i) % n_frames_exp;
            r.first_bad_m = m;
            r.first_bad_t = t;
            r.first_bad_expected = golden[i];
            r.first_bad_got = got[i];
        }
        sum_abs += d;
    }
    r.max_abs_diff = max_abs;
    r.mean_abs_diff = static_cast<float>(sum_abs / got.size());
    r.pass = (max_abs <= tol);
    return r;
}

void dumpFirstDivergences(MelExtractor const& mel, fs::path const& dir,
                          std::string const& name, int32_t max_dump)
{
    fs::path const pcm_path = dir / (name + ".pcm.f32");
    fs::path const mel_path = dir / (name + ".mel.f32");
    auto pcm = readF32(pcm_path);
    auto golden = readF32(mel_path);
    int32_t got_frames = 0;
    auto got = mel.compute(pcm, &got_frames);
    int32_t const n_mels = mel.n_mels();
    std::cerr << "  first " << max_dump << " divergent (m, t, expected, got, diff):\n";
    int32_t dumped = 0;
    for (size_t i = 0; i < got.size() && i < golden.size(); ++i)
    {
        float const d = std::abs(got[i] - golden[i]);
        if (d > 1e-3f)
        {
            int32_t const m = static_cast<int32_t>(i) / got_frames;
            int32_t const t = static_cast<int32_t>(i) % got_frames;
            std::cerr << "    (" << m << "," << t << ") exp=" << golden[i]
                      << " got=" << got[i] << " diff=" << d << "\n";
            if (++dumped >= max_dump) break;
        }
    }
    (void)n_mels;
}

} // namespace

int main(int argc, char** argv)
{
    if (argc < 4)
    {
        std::cerr << "Usage: " << argv[0]
                  << " <settings.json> <mel_filters.bin> <golden_dir>\n";
        return 2;
    }
    std::string settings_path = argv[1];
    std::string mel_bin_path = argv[2];
    fs::path golden_dir = argv[3];
    float tol = 1e-3f;

    MelExtractor mel(settings_path, mel_bin_path);

    fs::path index_path = golden_dir / "index.json";
    if (!fs::exists(index_path))
    {
        std::cerr << "golden index not found: " << index_path << "\n";
        return 2;
    }
    std::ifstream idx(index_path);
    Json index;
    idx >> index;
    auto const cases = index["cases"];

    std::printf("%-48s | %-9s | %-9s | %-12s | %-12s | %s\n",
                "test_case", "pcm_samp", "frames", "max_abs", "mean_abs", "PASS");
    std::printf("%s\n", std::string(48 + 3 + 9 + 3 + 9 + 3 + 12 + 3 + 12 + 3 + 4, '-').c_str());

    int pass_count = 0;
    int fail_count = 0;
    std::vector<CaseResult> results;
    for (auto const& c : cases)
    {
        std::string name = c.get<std::string>();
        auto r = evaluate(mel, golden_dir, name, tol);
        results.push_back(r);
        std::printf("%-48s | %9d | %5d/%-3d | %12.4e | %12.4e | %s\n",
                    name.c_str(), r.pcm_samples, r.got_frames, r.expected_frames,
                    r.max_abs_diff, r.mean_abs_diff, r.pass ? "PASS" : "FAIL");
        if (r.pass) ++pass_count;
        else ++fail_count;
    }

    std::printf("\n%d / %zu cases pass (tol = %.0e)\n", pass_count, cases.size(), tol);

    if (fail_count > 0)
    {
        // Dump first 10 divergent for the first failing case.
        for (auto const& r : results)
        {
            if (!r.pass)
            {
                std::cerr << "\nfirst failure: " << r.name
                          << "  max_abs=" << r.max_abs_diff
                          << "  worst @ m=" << r.first_bad_m << " t=" << r.first_bad_t
                          << "  exp=" << r.first_bad_expected
                          << "  got=" << r.first_bad_got << "\n";
                dumpFirstDivergences(mel, golden_dir, r.name, 10);
                break;
            }
        }
        return 1;
    }
    return 0;
}
